version: '3.9'

services:
  db:
    image: postgres:15
    container_name: db
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: django
    command: gunicorn habit_tracker.wsgi:application --bind 0.0.0.0:8000
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    user: "1000:1000"

  celery:
    build: .
    container_name: celery
    command: celery -A habit_tracker worker -l info
    env_file: .env
    depends_on:
      - web
      - redis
      - db
    user: "1000:1000"

  celery-beat:
    build: .
    container_name: celery-beat
    command: celery -A habit_tracker beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file: .env
    depends_on:
      - web
      - redis
      - db
    user: "1000:1000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  postgres_data:
